### ISSUE TITLE
No method matching from_grib_date_time(::Int32, ::Int32; epoch::Dates.DateTime)

### ISSUE THREAD

**Issue by lupemba** [JuliaGeo/GRIBDatasets.jl#25]
I am trying to read data from ERA5 data with the package https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview 
The file is 300 MB so I have not attached it here.

I get this error. 
`ERROR: MethodError: no method matching from_grib_date_time(::Int32, ::Int32; epoch::Dates.DateTime)`

I can see that the function is definite 
```Julia
from_grib_date_time(date::Int, time::Int; epoch::DateTime=DEFAULT_EPOCH)::Int
```
but looking at the code I think the more generic Integer type should be used instead.
```Julia
from_grib_date_time(date::Integer , time::Integer ; epoch::DateTime=DEFAULT_EPOCH)::Integer 
```

**Comment by tcarion** [comment]
solved by #26
