### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/GRIBDatasets.jl#3]
This is looking pretty good. 

Do you need any help getting this registered? It's also possible to do that under JuliaGeo if you want more help with ongoing maintenance.

**Comment by tcarion** [comment]
Yes, would be nice to make it under JuliaGeo!
I kind of see how to normally register a package, but I have no idea how to do it under another organization. Could you point me in right direction? Thanks!

**Comment by rafaqz** [comment]
Great. You would need to transfer the package to the org, then I can give you owner permissions for it and you can register as usual. It's fine if you want to keep it under your own name though, this is just the kind of technical low-level package that is often in JuliaGeo so we share the maintenance.

To register you just can use (at)JuliaRegistrator register in a github comment on a commit with passing tests that you are happy with registering.

**Comment by tcarion** [comment]
Alright, what do I have to do to transfer the package to the org? Should I already register the package or should I wait for it to be transferred first?

**Comment by rafaqz** [comment]
Either is fine, bit you will need to make a registry PR if if register before transfer.

Transfers are near delete on the github settings, just put in JuliaGeo. I will accept it and make you the owner.

**Comment by tcarion** [comment]
I asked for the transfer and got a "You don’t have the permission to create public repositories on JuliaGeo". I guess that means you received the request, let me know if you don't :-)

**Comment by rafaqz** [comment]
I invitee you as a member, that should make it easier

**Comment by tcarion** [comment]
Thanks, I accepted the membership, but I still get the same error message from GitHub when I try to transfer the package. Are there some permissions I need to be granted to be able to transfer it?

**Comment by rafaqz** [comment]
Oh sorry I've just gone and fixed the JuilaGeo permissions so members can create packages. Try again and see if that worked.

**Comment by tcarion** [comment]
Thanks, everything worked fine, and I made the registration PR: https://github.com/JuliaRegistries/General/pull/73630

**Comment by tcarion** [comment]
One more thing, is that possible for you to give me more permissions on the repo, so I can easily push and update the settings (namely for repairing the broken docs link)? Thanks!

**Comment by rafaqz** [comment]
You have an Admin role now. I can give you admin for all of JuliaGeo if you want to also work on the other packages, but best not to if you don't intend to do that.

**Comment by tcarion** [comment]
Perfect thank you! Yes, let's leave it like that for now

**Comment by tcarion** [comment]
It now has been registered, I close the issue
