### ISSUE TITLE
code sharing with NCDatasets?

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaGeo/GRIBDatasets.jl#7]
@tcarion  Thank you for sharing this nice package! I am developping with NCDatasets.jl packages and it seems that we have similar goals :-)
Would it be useful that I factor out some code of the of NCDatatasets.jl in a separate package (maybe AbstractDatasets.jl in JuliaGeo) to share common functionalities? "AbstractDatasets.jl" would be a pure julia package (without dependency to NetCDF_jll) with some abstract type definition, so that a use can more easily write code that seamless work with both packages.

Maybe also the multi-file support could be part of this package? 

The idea is that GRIBDatasets.jl and NCDatasets.jl would have this package as a dependency and that our main types (like dataset) would derive from it.

**Comment by tcarion** [comment]
Hi! That's a very good idea, this could simplify the integration of netcdf and GRIB files into Rasters.jl (GRIB support is ongoing, see https://github.com/rafaqz/Rasters.jl/pull/283), which I think is a good point. I tried to follow the structure of NCDatasets.jl for developing GRIBDatasets.jl, so it shouldn't be too difficult to make them work together!

**Comment by Alexander-Barth** [comment]
Thank you so much for your positive feedback! This is great!

Sometimes, I need to know all the dimensions defined in a datasets, and I currently use `ds.dim` for this.

Some small difference, that I am seeing is that GRIDDatasets uses the pluralized form `ds.dims`:

https://github.com/JuliaGeo/GRIBDatasets.jl/blob/main/src/dataset.jl#L69

Even if there are several typically several dimensions, I uses the singular form in  (like `ds.attrib`). Would you welcome a PR changer ds.dims -> ds.dim or should be rather have a function like `some_function(ds)` which would the underlying `ds.dim(s)` ?

**Comment by tcarion** [comment]
You're right, it's better to be consistent and change this to `ds.dim`. I can try to prepare the PR when I have a little bit of time!

**Comment by Alexander-Barth** [comment]
Another small difference is that `ds.dims["dim_name"]` returns a `GRIBDatasets.Dimension` while in NCDatasets case it is just a number. That might be more difficult to change has you have the types `Vertical`, `Horizontal`, ....

**Comment by Alexander-Barth** [comment]
By the way, I can make such PR as well :-)

**Comment by tcarion** [comment]
I actually had in mind to simplify the implementation of dimensions in GRIBDatasets, I think I made it pointlessly complicated. There's the `new-dims-impl` branch where I started to work on it, but I got deviated from it because of more urgent other projects. I'll try to get back to it, keeping the `NCDasatets` logic in sight to make it more consistent!

**Comment by tcarion** [comment]
Meanwhile working more in-depth on the reimplementation of Dimensions, I made the few changes mentioned above and open the pull request

**Comment by Alexander-Barth** [comment]
This is great, thank you so much. I just tested the PR, and I did not see any difference relative to the use of the `dim`.

**Comment by tcarion** [comment]
Yes that sounds great! Should this package be created directly on JuliaGeo?

**Comment by Alexander-Barth** [comment]
Yes, I think having this package on JuliaGeo would be good so that it is easier for you to make changes if necessary.

**Comment by Alexander-Barth** [comment]
Here is it:
https://github.com/JuliaGeo/AbstractDatasets.jl

If this is ok for you, I go ahead an try to register this package so that we can depend on it.

**Comment by tcarion** [comment]
Awesome, thanks! I'll keep implementing the interface once it's registered (I think I'll push new stuff to #8 )

**Comment by Alexander-Barth** [comment]
Great! I just made a PR to register [AbstractDatasets.jl](https://github.com/JuliaGeo/AbstractDatasets.jl)

https://github.com/JuliaRegistries/General/pull/79180#issuecomment-1460444882

**Comment by Alexander-Barth** [comment]
In the end, I had to choose a different name of this package:
https://github.com/JuliaGeo/CommonDataModel.jl

As a proof concept, I used your approach (using a non-netcdf data format, accessing it with a the NetCDF/CommonDataModel API) for GeoTIFFs. It helped a lot to find out which functions needs to be factor-out from NCDatasets:

https://github.com/Alexander-Barth/TIFFDatasets.jl

TIFFDatasets.jl uses now the `show` methods in CommonDataModel.jl (previously from NCDatasets) and query various metadata. Obviously, you can still use your current show methods. But you can delegate this to CommonDataModel.jl if you want :-)

**Comment by tcarion** [comment]
That's great, thanks! I see in the tests of CommonDataModel that you can easily convert a GRIB file to NetCDF, that's pretty amazing! Probably not as efficient as using the dedicated `grib_convert` binary, but being able to do it in Julia is very nice.

I started implementing the interface for GRIBDatasets, but I'm facing a little issue (#8 )

**Comment by Alexander-Barth** [comment]
Yes, not sure if it would be as efficient as `grib_convert` (could be :-)) but I think it is a good test to see if the general approach works and if all information is accessible via the CommonDataModel API.

**Comment by tcarion** [comment]
I guess this is solved by https://github.com/JuliaGeo/GRIBDatasets.jl/pull/8. But I propose to close this when we are sure that the conversion from GRIB to netCDF works :)
